[directories]
; Пути Asterisk
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[options]
; Основные опции
verbose = 3
debug = 0
alwaysfork = yes
nofork = no
quiet = no
timestamp = yes
execincludes = yes
internal_timing = yes
systemname = gochs-pbx
languageprefix = yes

; Лимиты
maxcalls = 100
maxload = 0.9
minmemfree = 100

; Консоль
console = no
nocolor = no

; Дамп при падении
dumpcore = yes

; Транскодинг
transcode_via_sln = yes
transmit_silence = yes

; Совместимость
[compat]
pbx_realtime = 1.6
res_agi = 1.6
app_set = 1.6

; Файлы управления
[files]
astctlpermissions = 0660
astctlowner = asterisk
astctlgroup = asterisk
astctl = asterisk.ctl
