; =====================================================
; Настройки аудио кодеков
; =====================================================

[opus]
type = codec
packet_loss = 0
max_bandwidth = wide
bitrate = 16000

[g729]
type = codec
bitrate = 8000

[ulaw]
type = codec
bitrate = 64000

[alaw]
type = codec
bitrate = 64000

[gsm]
type = codec
bitrate = 13000

[g722]
type = codec
bitrate = 64000
