; =====================================================
; Дополнительные функции
; =====================================================

[general]
featuredigittimeout = 1000
courtesytone = beep
transferdigittimeout = 3
atxfernoanswertimeout = 15
atxferdropcall = no
atxferloopdelay = 10
atxfercallbackretries = 2
pickupexten = *8
pickupsound = beep
pickupfailsound = beeperr

[featuremap]
blindxfer => #1
atxfer => *2
disconnect => *0
automon => *3
