; =====================================================
; HTTP сервер Asterisk (для ARI)
; =====================================================

[general]
enabled = yes
bindaddr = 127.0.0.1
bindport = 8088
tlsenable = no
tlscertfile = /etc/asterisk/keys/asterisk.crt
tlsprivatekey = /etc/asterisk/keys/asterisk.key
prefix = ari
enablestatic = yes
sessionlimit = 100
websocket_write_timeout = 100
allowed_origins = http://localhost:3000,https://{{DOMAIN_OR_IP}}

[gochs]
read_only = no
password_format = plain
password = {{ASTERISK_ARI_PASSWORD}}

[monitor]
read_only = yes
password_format = plain
password = {{ASTERISK_MONITOR_PASSWORD}}
